server:
  port: 8761  # default Eureka server port

spring:
  application:
    name: EUREKA-SERVER

eureka:
  client:
    register-with-eureka: false  # Server does not register itself
    fetch-registry: false        # Server does not query itself
