server:
  port: 8761  # default Eureka server port

spring:
  application:
    name: EUREKA-SERVER

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info, metrics

eureka:
  client:
    register-with-eureka: false  # Server does not register itself
    fetch-registry: false        # Server does not query itself
